import { Fragment } from "react";
import Head from "next/head";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import ScrollIndicator from "@/components/scrollIndicator/ScrollIndicator";
import { App, Main } from "@/components/content";

export default function Layout(props) {
  const { title, children, className } = props;

  return (
    <Fragment>
      <Head>
        <title>{title ? title : "Default Title"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <App className={className}>
        <Header />
        <Main>{children}</Main>
        <Footer />
        <ScrollIndicator />
      </App>
    </Fragment>
  );
}
